# action.yml
name: 'Sync Code'
description: 'Sync between alicode and github'
inputs:
  project:  # id of input
    description: 'project name'
    required: true
    default: ''
  private-key:  # id of input
    description: 'the key to decode private action'
    required: true
    default: ''
  root_folder:
    description: 'Terraform folder'
    required: true
    default: ''
  cmd:  # id of input
    description: 'Terraform commond'
    required: true
    default: ''
outputs:
  run_log: 
    description: 'run_log'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}  
    - ${{ inputs.private-key }}
    - ${{ inputs.root_folder }}
    - ${{ inputs.cmd }}
 